# Generated by Django 5.1.6 on 2025-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
